# Generated by Django 3.1 on 2020-09-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('groupID', models.IntegerField(primary_key=True, serialize=False)),
                ('categoryID', models.IntegerField(db_index=True)),
                ('groupName', models.CharField(max_length=100, null=True)),
                ('iconID', models.IntegerField(null=True)),
                ('useBasePrice', models.BooleanField(null=True)),
                ('anchored', models.BooleanField(null=True)),
                ('anchorable', models.BooleanField(null=True)),
                ('fittableNonSingleton', models.BooleanField(null=True)),
                ('published', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'invGroups',
            },
        ),
    ]
