version: '3.3'

services:
  web:
    build: .
    command: gunicorn taxsysv3.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - /home/rancher/data/taxsysv3/settings.py:/code/taxsysv3/settings.py
      - static_volume:/code/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=taxsysv3.binarymethod.com
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  taxsys_postgres_data:
  taxsys_static_volume:
