version: '3.7'

services:
  web:
    build: .
    command: gunicorn taxsysv3.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - type: bind
        source: c:/Docker/taxsysv3/settings.py
        target: /code/DockerTest/settings.py
      - static_volume:/code/staticfiles
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
