# Generated by Django 3.1 on 2020-08-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMaterials',
            fields=[
                ('typeID', models.IntegerField(primary_key=True, serialize=False)),
                ('materialTypeID', models.IntegerField(db_index=True)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'invTypeMaterials',
            },
        ),
    ]
