# Generated by Django 3.1.4 on 2020-12-16 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import secrets
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(default=uuid.uuid4, max_length=255)),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('mineral_tax_rate', models.IntegerField(default=5)),
                ('goo_tax_rate', models.IntegerField(default=5)),
                ('source', models.IntegerField(default=60003760)),
                ('source_type', models.CharField(default='buy', max_length=4)),
                ('source_stat', models.CharField(default='percentile', max_length=50)),
                ('source_modifier', models.IntegerField(default=90)),
                ('ice_refine_rate', models.FloatField(default=89.3)),
                ('ore_refine_rate', models.FloatField(default=89.3)),
                ('moon_refine_rate', models.FloatField(default=89.3)),
                ('late_fees_enabled', models.BooleanField(default=False)),
                ('late_fee_threshold', models.IntegerField(default=0)),
                ('late_fee_day', models.IntegerField(default=-1)),
                ('late_fee_charge', models.IntegerField(default=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('corporation_id', models.IntegerField()),
                ('ceo_id', models.IntegerField()),
                ('last_pull', models.DateField(null=True)),
                ('process_payments', models.BooleanField(default=False)),
                ('process_taxes', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('isValid', models.BooleanField(default=False)),
                ('join_date', models.DateField()),
                ('start_date', models.DateField(null=True)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.corporation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
