# Generated by Django 3.0.4 on 2020-04-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Override',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenantID', models.IntegerField(null=True)),
                ('typeID', models.IntegerField()),
                ('tax', models.FloatField()),
                ('isOre', models.BooleanField(default=False)),
            ],
        ),
    ]
