# Generated by Django 3.1.4 on 2020-12-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='source',
            field=models.IntegerField(choices=[('60003760', 'Jita'), ('60008494', 'Amarr'), ('60011866', 'Dodixie'), ('60004588', 'Rens'), ('60005686', 'Hek')], default=60003760),
        ),
        migrations.AlterField(
            model_name='setting',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
