# Generated by Django 3.1 on 2020-12-03 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='ceo_subject',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='corporation_id',
        ),
        migrations.AlterField(
            model_name='override',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('corporation_id', models.IntegerField()),
                ('ceo_id', models.IntegerField()),
                ('ceo_name', models.CharField(max_length=255)),
                ('last_pull', models.DateField(null=True)),
                ('processPayments', models.BooleanField(default=False)),
                ('processTaxes', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
        ),
    ]
