# Generated by Django 3.1.4 on 2020-12-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20201217_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='late_fee_day',
            field=models.IntegerField(choices=[(-1, 'Pick a day...'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (30, 'Last Day...')], default=-1),
        ),
        migrations.AlterField(
            model_name='setting',
            name='source',
            field=models.IntegerField(choices=[(60003760, 'Jita'), (60008494, 'Amarr'), (60011866, 'Dodixie'), (60004588, 'Rens'), (60005686, 'Hek')], default=60003760),
        ),
        migrations.AlterField(
            model_name='setting',
            name='source_stat',
            field=models.CharField(choices=[('weightedAverage', 'Weighted Average'), ('max', 'Max Price'), ('min', 'Min Price'), ('stddev', 'Standard Deviation'), ('median', 'Median'), ('percentile', 'Percentile')], default='percentile', max_length=50),
        ),
        migrations.AlterField(
            model_name='setting',
            name='source_type',
            field=models.CharField(choices=[('buy', 'Buy Orders'), ('sell', 'Sell Orders')], default='buy', max_length=4),
        ),
    ]
