# Generated by Django 3.1 on 2020-12-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_auto_20201203_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='tenant_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='tenant',
            name='identifier',
            field=models.CharField(default='blah', max_length=255),
            preserve_default=False,
        ),
    ]
