# Generated by Django 3.1.4 on 2020-12-07 10:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='identifier',
            field=models.CharField(default=uuid.UUID('b7681891-b1ca-491f-9f3c-5677d9c35b43'), max_length=255),
        ),
    ]
