# Generated by Django 3.1.4 on 2020-12-07 10:44

from django.db import migrations, models
import secrets
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0008_auto_20201207_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='identifier',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='token',
            field=models.CharField(default=secrets.token_urlsafe, max_length=100),
        ),
    ]
