# Generated by Django 3.1.4 on 2020-12-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0009_auto_20201207_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporation',
            name='ceo_name',
        ),
    ]
