# Generated by Django 3.1.4 on 2020-12-13 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0010_remove_corporation_ceo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
