# Generated by Django 3.1.4 on 2020-12-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0011_character_join_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corporation',
            old_name='processPayments',
            new_name='process_payments',
        ),
        migrations.RenameField(
            model_name='corporation',
            old_name='processTaxes',
            new_name='process_taxes',
        ),
    ]
