# Generated by Django 3.1.4 on 2020-12-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0012_auto_20201214_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
    ]
