# Generated by Django 3.1.4 on 2020-12-15 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0013_auto_20201215_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('mineral_tax_rate', models.IntegerField(default=5)),
                ('goo_tax_rate', models.IntegerField(default=5)),
                ('source', models.IntegerField(default=60003760)),
                ('source_type', models.CharField(default='buy', max_length=4)),
                ('source_stat', models.CharField(default='percentile', max_length=50)),
                ('source_modifier', models.IntegerField(default=90)),
                ('ice_refine_rate', models.FloatField(default=89.3)),
                ('ore_refine_rate', models.FloatField(default=89.3)),
                ('moon_refine_rate', models.FloatField(default=89.3)),
                ('late_fees_enabled', models.BooleanField(default=False)),
                ('late_fee_threshold', models.IntegerField(default=0)),
                ('late_fee_day', models.IntegerField(default=-1)),
                ('late_fee_charge', models.IntegerField(default=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
        ),
        migrations.DeleteModel(
            name='Override',
        ),
    ]
