# Generated by Django 3.1.4 on 2020-12-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightedAverage', models.DecimalField(decimal_places=2, max_digits=19)),
                ('max', models.DecimalField(decimal_places=2, max_digits=19)),
                ('min', models.DecimalField(decimal_places=2, max_digits=19)),
                ('stddev', models.DecimalField(decimal_places=2, max_digits=19)),
                ('median', models.DecimalField(decimal_places=2, max_digits=19)),
                ('volume', models.BigIntegerField()),
                ('orderCount', models.BigIntegerField()),
                ('percentile', models.DecimalField(decimal_places=2, max_digits=19)),
                ('date', models.DateField()),
                ('typeID', models.IntegerField()),
            ],
        ),
    ]
