# Generated by Django 3.0.2 on 2020-01-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testuser',
            name='last_alt_check',
            field=models.DateField(null=True),
        ),
    ]
