# Generated by Django 3.1.4 on 2020-12-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testauth', '0003_auto_20200817_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='last_alt_check',
            field=models.DateField(blank=True, null=True),
        ),
    ]
