# Generated by Django 3.0.2 on 2020-01-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testauth_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testuser',
            name='auth_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testuser',
            name='subject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
