# Generated by Django 3.0.2 on 2020-01-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testauth_module', '0002_auto_20200126_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='auth_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='testuser',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
