# Generated by Django 3.0.2 on 2020-01-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testauth_module', '0004_testuser_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testuser',
            name='is_sync',
            field=models.BooleanField(default=False),
        ),
    ]
