# Generated by Django 3.1 on 2020-08-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('typeID', models.IntegerField(primary_key=True, serialize=False)),
                ('groupID', models.IntegerField(db_index=True, null=True)),
                ('typeName', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('mass', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('capacity', models.FloatField(null=True)),
                ('portionSize', models.IntegerField(null=True)),
                ('raceID', models.IntegerField(null=True)),
                ('basePrice', models.DecimalField(decimal_places=4, max_digits=19)),
                ('published', models.BooleanField(null=True)),
                ('marketGroupID', models.IntegerField(null=True)),
                ('iconID', models.IntegerField(null=True)),
                ('soundID', models.IntegerField(null=True)),
                ('graphicID', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'invTypes',
            },
        ),
    ]
