# Generated by Django 3.1 on 2020-09-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketGroups',
            fields=[
                ('marketGroupID', models.IntegerField(primary_key=True, serialize=False)),
                ('parentGroupID', models.IntegerField(null=True)),
                ('marketGroupName', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=3000, null=True)),
                ('iconID', models.IntegerField(null=True)),
                ('hasTypes', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'invMarketGroups',
            },
        ),
    ]
